sudo: false
language: node_js
node_js:
  - '10'
branches:
  only:
    - master
    - develop
script:
  - npm run test && npm run build
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/cobertura.xml
cache:
  directories:
    - node_modules
