name: Node CI

on:
  push:
    branches:
      - master
      - develop
      - 'dependabot/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      # See below: Test Browser
      #- name: Install Chromium
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -yq libgconf-2-4
      #    sudo apt-get install -y wget --no-install-recommends
      #    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      #    sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      #    sudo apt-get update
      #    sudo apt-get install -y google-chrome-unstable --no-install-recommends

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

      - name: ESLint Check
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: lint

      # ChromeHeadless cannot be captured. skipped
      #- name: Test Browser
      #  uses: Borales/actions-yarn@v2.1.0
      #  with:
      #    cmd: test:browser
      #  env:
      #    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      #    CHROME_BIN: /usr/bin/google-chrome-unstable
      - name: Test Node
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: test:node

      - name: Build
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: build
